### ISSUE TITLE
error in classificaton other letters

### ISSUE THREAD

**Issue by itays02** [vedaldi/practical-cnn#9]
Hello. 
I'm using your library for Hebrew letters classification. After updating the imdb variable, I've got today an exception of index out of " Index exceeds matrix dimensions." in vlnnloss)

The new image/ kabels db is identical to the first one(classing chars).

Appreciate your help,

-------------------------------------------- CODE  ---------------------------------------------------------------------
     layer|      0|      1|      2|      3|      4|      5|      6|      7|      8|
      type|  input|   conv|  mpool|   conv|  mpool|   conv|   relu|   conv|softmxl|
      name|    n/a|       |       |       |       |       |       |       |       |
----------|-------|-------|-------|-------|-------|-------|-------|-------|-------|
   support|    n/a|      5|      2|      5|      2|      4|      1|      2|      1|
  filt dim|    n/a|      1|    n/a|     20|    n/a|     50|    n/a|    500|    n/a|
 num filts|    n/a|     20|    n/a|     50|    n/a|    500|    n/a|     26|    n/a|
    stride|    n/a|      1|      2|      1|      2|      1|      1|      1|      1|
       pad|    n/a|      0|      0|      0|      0|      0|      0|      0|      0|
----------|-------|-------|-------|-------|-------|-------|-------|-------|-------|
   rf size|    n/a|      5|      6|     14|     16|     28|     28|     32|     32|
 rf offset|    n/a|      3|    3.5|    7.5|    8.5|   14.5|   14.5|   16.5|   16.5|
 rf stride|    n/a|      1|      2|      2|      4|      4|      4|      4|      4|
----------|-------|-------|-------|-------|-------|-------|-------|-------|-------|
 data size|NaNxNaN|NaNxNaN|NaNxNaN|NaNxNaN|NaNxNaN|NaNxNaN|NaNxNaN|NaNxNaN|NaNxNaN|
data depth|    NaN|     20|     20|     50|     50|    500|    500|     26|      1|
  data num|    100|    100|    100|    100|    100|    100|    100|    100|      1|
----------|-------|-------|-------|-------|-------|-------|-------|-------|-------|
  data mem|    NaN|    NaN|    NaN|    NaN|    NaN|    NaN|    NaN|    NaN|    NaN|
 param mem|    n/a|    2KB|     0B|   98KB|     0B|    2MB|     0B|  203KB|     0B|

parameter memory|2MB (4.8e+05 parameters)|
     data memory|NaN (for batch size 100)|

train: epoch 01:   1/ 76: 132.9 Hz obj:3.2 top1err:0.96 top5err:0.84 [100/100]
train: epoch 01:   2/ 76: Index exceeds matrix dimensions.

Error in vl_nnloss (line 209)
      t = Xmax + log(sum(ex,3)) - X(ci) ;

Error in vl_simplenn (line 293)
      res(i+1).x = vl_nnloss(res(i).x, l.class) ;

**Comment by rashaalshehhi** [comment]
I have same problem. How did you solved it?
